services:
  taksov:
    container_name: taksovcontainer
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: taksov:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}

