jwt:
  secret: ${JWT_SECRET}
server:
  port: ${HOST_PORT:8080}
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
      jdbc:
        time-zone: UTC
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
  management:
    endpoints:
      enabled-by-default: false
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}
    csrf: ${CSRF_ENABLED}
#      jmx.exposure.exclude: all
#      web.exposure.include: health
  data:
    web.pageable:
      max-page-size: 10
      one-indexed-parameters: true
logging:
  level:
    com.mat.taksov: debug
#    org.springframework.security: debug
    org:
      springframework:
        security: trace
        transaction: trace
        web.cors: debug
        web: debug


##updates database schema when changing the entity
#spring.jpa.hibernate.ddl-auto=update
#logging.level.org.springframework.security=DEBUG

##custom variable for example
#customenvironmentvariable=this is a custom environment variable
#
#current.profile=prod

#logging.level.org.springframework.security=TRACE # WARNING: TRACE HACE QUE OCURRA LAZY LOADING EXCEPTION, PREFERIR DEBUG.
# ESTO SUCEDE PORQUE EN TRACE INTENTA SERIALIZAR USER CON TASK Y ROLE DESPUES DE QUE LA SESION HTTP YA SE HA DESCONECTADO DE HIBERNATE

