
# SERVER CONFIG
CONTAINER_PORT: ${CONTAINER_PORT}
HOST_PORT: ${HOST_PORT}
ACTIVE_PROFILE: ${ACTIVE_PROFILE}

JWT_SECRET: ${JWT_SECRET}

# DATABASE
MYSQL_USERNAME: ${MYSQL_USERNAME}
MYSQL_PASSWORD: ${MYSQL_PASSWORD}
MYSQL_PORT: ${MYSQL_PORT}
MYSQL_DATABASE: ${MYSQL_DATABASE}
MYSQL_HOST: ${MYSQL_HOST}
DDL_AUTO: ${DDL_AUTO}

# CORS
ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
CSRF_ENABLED: ${CSRF_ENABLED}
  