# SERVER CONFIG
CONTAINER_PORT: 8000
HOST_PORT: 8080
ACTIVE_PROFILE: dev

JWT_SECRET: FIDJQ92P3J90P1283RH90P8HF2P938HF09182H3F098H1P39FI

# DATABASE
MYSQL_USERNAME: root
MYSQL_PASSWORD: admin123
MYSQL_PORT: 3306
MYSQL_DATABASE: dbtaksov2
MYSQL_HOST: localhost
DDL_AUTO: update

# CORS
ALLOWED_ORIGINS: "http://localhost:4200"
CSRF_ENABLED: false
  